# Intialized 08/09/2026
# Last edited 08/09/2026 by: Cirvam
#
# By Cirvam
#
#
# Front end for all functions in friends skript. What the player sees! Using functions here so that
# it is easier to stylize the front end messages the player sees, such as adding clickable buttons OTHER
# fancier request messages for example, while keeping the API consistent and so it needs least amount of tweaking.


function showFriendRequestSent(player: player, target: player): # Notify sender request was successfully sent
    send "&aFriend request sent to %name of {_target}%!" to {_player}

function showFriendRequestFailed(player: player): # Notify sender request has failed
    send "&cFriend request failed." to {_player}

function showFriendRequestReceived(sender: player, target: player): # Notify target a request is received.
    send "&e%name of {_sender}% &ahas sent you a friend request!" to {_target}

function showFriendRequestAccept(player: player, sender:player):
    send "&aYou accepted %name of {_sender}%'s friend request!" to {_player} # Notify player request accepted
    send "&a%name of {_player}% has accepted your friend request!" to {_sender} # Notify sender request accepted

function showFriendRequestAcceptFailed(player: player): # accept failure message
    send "&cCould not accept friend request" to {_player}

function showFriendRequestDeny(player: player, sender: player):
    send "&cFriend request from %name of {_sender}% declined." to {_player} # Notify player of decline
    send "&c%name of {_player}% has declined your friend request." to {_sender} # notify sender of decline

function showFriendRequestDenyFailed(player: player):
    send "&cCould not deny friend request. Something went wrong." to {_player}

function showFriendRemove(player: player, target: player): # Show removal message
    send "&e%{_target}% has been removed from your friends list." to {_player}

function showFriendRemoveFailed(player: player, target: player): # Removal message failed
    send "&c%{_target}% is not on your friends list." to {_player}

function showFriendRequests(player: player, requests: strings): # Show friend requests.
    set {_message} to friendHeader("Friend Requests")

    loop {_requests::*}:
        set {_message} to "%{_message}%%nl%&f - &e%getFriendName(loop-value)%"

    send {_message} to {_player}

function showFriends(player: player, friends: strings): # Packs players friend into a list and sends list.
    set {_message} to friendHeader("Friends")
    set {_online} to ""
    set {_offline} to ""

    if {_friends::*} is not set: # If no friends, tell user
        set {_message} to "&cYou don't have any friends yet."
        send {_message} to {_player}
        stop

    loop {_friends::*}: # Loop thru online and offline, pack into list with online showing first.
        if isFriendOnline(loop-value) is true:
            set {_online} to "%{_online}%%nl%&f- &a%getFriendName(loop-value)%"
        else:
            set {_offline} to "%{_offline}%%nl%&f- &c%getFriendName(loop-value)%"
    set {_message} to "%{_message}%%{_online}%%{_offline}%"
    send {_message} to {_player}
