# Intialized 08/09/2026
# Last edited 08/09/2026 by: Cirvam
#
# By Cirvam
#
#
# Front end for all functions in friends skript. What the player sees! Using functions here so that
# it is easier to stylize the front end messages the player sees, such as adding clickable buttons OTHER
# fancier request messages for example, while keeping the API consistent and so it needs least amount of tweaking.


function showFriendRequestSent(player: player, target: player): # Notify sender request was successfully sent
    send "&aFriend request sent to %name of {_target}%!" to {_player}

function showFriendRequestFailed(player: player): # Notify sender request has failed
    send "&cFriend request failed." to {_player}

function showFriendRequestReceived(sender: player, target: player): # Notify target a request is received.
    send "&e%name of {_sender}% &ahas sent you a friend request!" to {_target}

function showFriendRequestAccept(player: player, sender:player):
    send "&aYou accepted %name of {_sender}%'s friend request!" to {_player} # Notify player request accepted
    send "&a%name of {_player}% has accepted your friend request!" to {_sender} # Notify sender request accepted

function showFriendRequestAcceptFailed(player: player, sender: player): # accept failure message
    send "&cCould not accept friend request from %name of {_sender}%."

function showFriendRequestDeny(player: player, sender: player):
    send "&cFriend request from %name of {_sender}% declined." to player # Notify player of decline
    send "&c%name of {_player}% has declined your friend request." to sender # notify sender of decline

function showFriendRequestDenyFailed(player: player):
    send "&cCould not deny friend request. Something went wrong." to {_player}