# Commands file
# 
#
# Made by Cirvam
#
###################################

# CORE COMMANDS!!!
# Do not change unless you know what you're doing!!!

 
command /friend <text> [<player>]: # Base command
    permission: friendsapi.use
    permission message: "&cYou don't have permission to use this command!"
    usage: &cUsage: /friend <add | accept | deny | remove> <player>
    trigger:


########### friend add command #########

        if arg-1 is "add": 
            if arg-2 is not set:
                showFriendUsageAdd(player)
                stop
            
            if sendFriendRequest(player, arg-2) is true:
                showFriendRequestSent(player, arg-2)
                showFriendRequestReceived(player, arg-2)
            else:
                showFriendRequestFailed(player)

########### friend accept command ##########

        else if arg-1 is "accept":
            if arg-2 is not set:
                showFriendUsageAccept(player)
                stop

            if acceptFriendRequest(player, arg-2) is true:
                showFriendRequestAccept(player, arg-2)
            else:
                showFriendRequestAcceptFailed(player)
        

############### friend deny command ###########
            
        else if arg-1 is "deny":
            if arg-2 is not set:
                showFriendUsageDeny(player)
                stop

            if denyFriendRequest(player, arg-2) is true:
                showFriendRequestDeny(player, arg-2)
            else:
                showFriendRequestDenyFailed(player)
        


############# friend remove command #############

        else if arg-1 is "remove":
            if arg-2 is not set:
                showFriendUsageRemove(player)
                stop
            if removeFriend(player, arg-2) is true:
                showFriendRemove(player, arg-2)
            else:
                showFriendRemoveFailed(player, arg-2)



############ friend requests command ##############

        else if arg-1 is "requests":
            set {_requests::*} to getFriendRequests(player)

            if {_requests::*} is not set:
                send "&eYou have no pending friend requests." to player
                stop

            showFriendRequests(player, {_requests::*})


########### friend list command ##########
        else if arg-1 is "list":
            set {_friends::*} to getFriends(player)
            showFriends(player, {_friends::*})


########## Help command #############

        else if arg-1 is "help":
            showFriendHelp(player)

######### Run if no /friend arguments are properly fulfilled ########

        else:
            send {FriendsAPI::config::invalid-command} to player