# Commands file
# Intialized on 08/09/2026
# Last edited 08/09/2026 by: Cirvam
#
# Made by Cirvam

######## TEST COMMANDS ##########

command /testfriend <player>:
    trigger:
        if addFriend(player, arg-1) is true:
            send "Friendship created!" to player
        else:
            send "Could not create friendship." to player



command /testremove <player>:
    trigger:
        if removeFriend(player, arg-1) is true:
            send "Friendship removed!" to player
        else:
            send "Could not remove friendship" to player


###################################



#######################################
# CORE COMMANDS!!!
# Do not change unless you know what you're doing!!!


command /friend <text> [<player>]:
    usage: &cUsage: /friend <add | accept | deny> <player>
    trigger:
        if arg-1 is "add":
            if arg-1 is not set:
                send "&cUsage: /friend add <player>" to player
                stop
            
            if sendFriendRequest(player, arg-2) is true:
                showFriendRequestSent(player, arg-2)
                showFriendRequestReceived(player, arg-2)
            else:
                showFriendRequestFailed(player)

        else if arg-1 is "accept":
            if arg-2 is not set:
                send "&cUsage: /friend accept <player>" to player
                stop

            if acceptFriendRequest(player, arg-2) is true:
                showFriendRequestAccept(player, arg-2)
            else:
                showFriendRequestAcceptFailed(player)
        
        else if arg-1 is "deny":
            if arg-2 is not set:
                send "&cUsage: /friend deny <player>" to player
                stop

            if denyFriendRequest(player, arg-2) is true:
                showFriendRequestDeny(player, arg-2)
            else:
                showFriendRequestDenyFailed(player)
        
        else:
            send "&cUsage: /friend <add | accept |deny> <player>" to player