# Commands file
# Intialized on 08/09/2026
# Last edited 08/09/2026 by: Cirvam
#
# Made by Cirvam

######## TEST COMMANDS ##########

command /testfriend <player>:
    trigger:
        if addFriend(player, arg-1) is true:
            send "Friendship created!" to player
        else:
            send "Could not create friendship." to player



command /testremove <player>:
    trigger:
        if removeFriend(player, arg-1) is true:
            send "Friendship removed!" to player
        else:
            send "Could not remove friendship" to player


command /debugfriends:
    trigger:
        send "&eYour UUID: &f%uuid of player%" to player
        send "&eFriends:" to player

        loop {friends::%uuid of player%::*}:
            send "&f - %loop-index% = %loop-value%" to player

command /debugfriendsreal:
    trigger:
        send "Your UUID: %uuid of player%" to player
        send "Direct friend variable:" to player
        send "{friends::%uuid of player%::*}" to player

        loop {friends::%uuid of player%::*}:
            send "Index: %loop-index% | Value: %loop-value%" to player


command /cleanupfriends:
    trigger:
        delete {friends::12de7fe9-5c04-4b12-9835-6f41be07d597::<none>}
        delete {friends::<none>::12de7fe9-5c04-4b12-9835-6f41be07d597}
        send "&aMalformed friend variables removed." to player


###################################



#######################################
# CORE COMMANDS!!!
# Do not change unless you know what you're doing!!!

 
command /friend <text> [<player>]: # Base command
    usage: &cUsage: /friend <add | accept | deny> <player>
    trigger:


########### friend add command #########

        if arg-1 is "add": 
            if arg-1 is not set:
                send "&cUsage: /friend add <player>" to player
                stop
            
            if sendFriendRequest(player, arg-2) is true:
                showFriendRequestSent(player, arg-2)
                showFriendRequestReceived(player, arg-2)
            else:
                showFriendRequestFailed(player)

########### friend accept command ##########

        else if arg-1 is "accept":
            if arg-2 is not set:
                send "&cUsage: /friend accept <player>" to player
                stop

            if acceptFriendRequest(player, arg-2) is true:
                showFriendRequestAccept(player, arg-2)
            else:
                showFriendRequestAcceptFailed(player)
        

############### friend deny command ###########
            
        else if arg-1 is "deny":
            if arg-2 is not set:
                send "&cUsage: /friend deny <player>" to player
                stop

            if denyFriendRequest(player, arg-2) is true:
                showFriendRequestDeny(player, arg-2)
            else:
                showFriendRequestDenyFailed(player)
        


############# friend remove command #############

        else if arg-1 is "remove":
            if arg-2 is not set:
                send "&cUsage: /friend remove player" to player
                stop
            if removeFriend(player, arg-2) is true:
                showFriendRemove(player, arg-2)
            else:
                showFriendRemoveFailed(player, arg-2)



############ friend requests command ##############

        else if arg-1 is "requests":
            set {_requests::*} to getFriendRequests(player)

            if {_requests::*} is not set:
                send "&eYou have no pending friend requests." to player
                stop

            showFriendRequests(player, {_requests::*})


########### friend list command ##########
        else if arg-1 is "list":
            set {_friends::*} to getFriends(player)
            showFriends(player, {_friends::*})


######### Run if no /friend arguments are properly fulfilled ########

        else:
            send "&cIncorect usage! See /friend help for all options." to player