# Commands file
# Intialized on 08/09/2026
# Last edited 08/09/2026 by: Cirvam
#
# Made by Cirvam

######## TEST COMMANDS ##########

command /testfriend <player>:
    trigger:
        if addFriend(player, arg-1) is true:
            send "Friendship created!" to player
        else:
            send "Could not create friendship." to player



command /testremove <player>:
    trigger:
        if removeFriend(player, arg-1) is true:
            send "Friendship removed!" to player
        else:
            send "Could not remove friendship" to player


###################################



######## COMMANDS #########